version: '3.7'

services:
  php-fpm:
    container_name: tmpdir
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - .:/var/www/html/:rw
      - ./vendor/:/var/www/html/vendor:rw
